export const ACTION_TYPE_INGREDIENTS = {
    ADD : 'ADD',
    REMOVE : 'REMOVE',
    FETCH_ALL : 'FETCH_ALL',
    SET_INGREDIENTS : 'SET_INGREDIENTS'
}
export const ACTION_AUTH = {
    AUTH_START : 'AUTH_START',
    AUTH_SUCCESS : 'AUTH_SUCCESS',
    AUTH_LOGOUT : 'AUTH_LOGOUT'
}

export const PURCHASE_BURGER_START = "PURCHASE_BURGER_START";
export const PURCHASE_BURGER_SUCCES = "PURCHASE_BURGER_SUCCES";
export const PURCHASE_BURGER_FAIL = "PURCHASE_BURGER_FAIL";
export const PURCHASE_INIT = "PURCHASE_INIT";
